import { NextRequest, NextResponse } from 'next/server';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_OWNER = process.env.GITHUB_OWNER;
const GITHUB_REPO = process.env.GITHUB_REPO;
const GITHUB_BRANCH = process.env.GITHUB_BRANCH || 'main';

interface FileToCommit {
  path: string;
  content: string;
}

async function getFileSha(path: string): Promise<string | null> {
  try {
    const response = await fetch(
      `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/contents/${path}?ref=${GITHUB_BRANCH}`,
      {
        headers: {
          Authorization: `Bearer ${GITHUB_TOKEN}`,
          Accept: 'application/vnd.github.v3+json',
        },
      }
    );
    
    if (response.ok) {
      const data = await response.json();
      return data.sha;
    }
    return null;
  } catch {
    return null;
  }
}

async function commitFile(file: FileToCommit, retries = 3): Promise<{ success: boolean; error?: string }> {
  for (let attempt = 0; attempt < retries; attempt++) {
    try {
      // Always fetch fresh SHA right before commit
      const sha = await getFileSha(file.path);
      
      const body: Record<string, string> = {
        message: `Update ${file.path} via Admin Panel`,
        content: Buffer.from(file.content).toString('base64'),
        branch: GITHUB_BRANCH,
      };
      
      if (sha) {
        body.sha = sha;
      }
      
      const response = await fetch(
        `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/contents/${file.path}`,
        {
          method: 'PUT',
          headers: {
            Authorization: `Bearer ${GITHUB_TOKEN}`,
            Accept: 'application/vnd.github.v3+json',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(body),
        }
      );
      
      if (response.ok) {
        return { success: true };
      }
      
      const errorData = await response.json();
      
      // If SHA mismatch, retry with fresh SHA
      if (response.status === 409 && attempt < retries - 1) {
        console.log(`SHA mismatch for ${file.path}, retrying...`);
        await new Promise(r => setTimeout(r, 500)); // Wait 500ms before retry
        continue;
      }
      
      console.error(`GitHub API error for ${file.path}:`, errorData);
      return { success: false, error: errorData.message || `HTTP ${response.status}` };
    } catch (error) {
      console.error(`Error committing ${file.path}:`, error);
      if (attempt === retries - 1) {
        return { success: false, error: String(error) };
      }
    }
  }
  return { success: false, error: 'Max retries exceeded' };
}

export async function POST(request: NextRequest) {
  try {
    if (!GITHUB_TOKEN || !GITHUB_OWNER || !GITHUB_REPO) {
      return NextResponse.json(
        { error: 'GitHub credentials not configured' },
        { status: 500 }
      );
    }

    const { heroes, skills, talents, mounts } = await request.json();
    
    const files: FileToCommit[] = [];
    
    // Generate TypeScript files
    if (heroes) {
      files.push({
        path: 'src/data/heroes.ts',
        content: `// Auto-generated by Viking Rise Admin\nexport const heroes = ${JSON.stringify(heroes, null, 2)};\n`,
      });
    }
    
    if (skills) {
      files.push({
        path: 'src/data/skills.ts',
        content: `// Auto-generated by Viking Rise Admin\nexport const skills = ${JSON.stringify(skills, null, 2)};\n`,
      });
    }
    
    if (talents) {
      files.push({
        path: 'src/data/talents.ts',
        content: `import { Talent } from '@/types';\n\n// Auto-generated by Viking Rise Admin\nexport const talents: Talent[] = ${JSON.stringify(talents, null, 2)};\n`,
      });
    }
    
    if (mounts) {
      files.push({
        path: 'src/data/mounts.ts',
        content: `import { Mount, MountSkill } from '@/types';\n\n// Auto-generated by Viking Rise Admin\nexport const mountSkills: MountSkill[] = [];\nexport const mounts: Mount[] = ${JSON.stringify(mounts, null, 2)};\n`,
      });
    }
    
    // Test GitHub connection first
    const testResponse = await fetch(
      `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}`,
      {
        headers: {
          Authorization: `Bearer ${GITHUB_TOKEN}`,
          Accept: 'application/vnd.github.v3+json',
        },
      }
    );
    
    if (!testResponse.ok) {
      const errorData = await testResponse.json();
      return NextResponse.json(
        { 
          error: 'GitHub connection failed', 
          details: errorData.message,
          hint: testResponse.status === 401 
            ? 'Token is invalid or expired. Generate a new one at github.com/settings/tokens'
            : testResponse.status === 404
            ? `Repository ${GITHUB_OWNER}/${GITHUB_REPO} not found. Check GITHUB_OWNER and GITHUB_REPO.`
            : 'Check your GitHub credentials'
        },
        { status: 500 }
      );
    }

    // Commit files sequentially to avoid race conditions
    const results: { success: boolean; error?: string }[] = [];
    for (const file of files) {
      const result = await commitFile(file);
      results.push(result);
      if (!result.success) break; // Stop on first error
    }
    const allSuccess = results.every(r => r.success);
    
    if (allSuccess) {
      return NextResponse.json({
        success: true,
        message: `Deployed ${files.length} files to GitHub. Vercel will auto-deploy in ~2 minutes.`,
        files: files.map(f => f.path),
      });
    } else {
      const errors = results.filter(r => !r.success).map(r => r.error);
      return NextResponse.json(
        { error: 'Some files failed to deploy', details: errors.join(', ') },
        { status: 500 }
      );
    }
  } catch (error) {
    console.error('Deploy error:', error);
    return NextResponse.json(
      { error: 'Deploy failed', details: String(error) },
      { status: 500 }
    );
  }
}
