// Auto-generated by Viking Rise Admin
export const skills = [
  {
    "id": 1,
    "name": "Furious Hack and Slash",
    "type": "Cooperation",
    "probability": 100,
    "description": "When deployed Troop performs a basic attack, there is a 20% chance to inflict Bleed on the target, dealing continuous damage every second (Damage Factor 350) for 2s. There is also a 15% chance for this hero Troop to recover 60 Rage, and a 15% chance to inflict Silence on the target for 1s.",
    "icon": "/images/skills/diamond/Furious-Hack-and-Slash.png",
    "effects": {
      "bleed": true,
      "basicattack": true,
      "rage": true,
      "silence": true
    }
  },
  {
    "id": 2,
    "name": "Poison Arrow",
    "type": "Command",
    "probability": 100,
    "description": "When deployed Troop performs a basic attack, there is a 25% chance to inflict Poison on the target, dealing continuous damage every second (Damage Factor 300) for 3s.",
    "icon": "/images/skills/diamond/Poison-Arrow.png",
    "effects": {
      "poison": true
    }
  },
  {
    "id": 3,
    "name": "Shield Wall",
    "type": "Passive",
    "probability": 100,
    "description": "Increases Defense of up to 4 ally troops in a circular range by 30% for 8 seconds. Also provides a shield that absorbs damage equal to 20% of max HP.",
    "icon": "/images/skills/diamond/Shield-Support.png",
    "effects": {
      "shield": true,
      "buff": true
    }
  },
  {
    "id": 4,
    "name": "Healing Light",
    "type": "Active",
    "probability": 100,
    "description": "Restores Health of up to 4 ally troops in a circular range by 25% of max HP. Also removes all debuffs from affected troops.",
    "icon": "/images/skills/diamond/Blessed-Healing.png",
    "effects": {
      "heal": true,
      "purify": true
    }
  },
  {
    "id": 5,
    "name": "Counter Strike",
    "type": "Counterattack",
    "probability": 100,
    "description": "When attacked, there is a 30% chance to counterattack, dealing damage equal to 150% of basic attack damage.",
    "icon": "/images/skills/diamond/Counterstrike.png",
    "effects": {
      "counterattack": true,
      "directdamage": true
    }
  },
  {
    "id": 6,
    "name": "Fireball",
    "type": "Active",
    "probability": 100,
    "description": "Launches a fireball at the target, dealing damage equal to 200% of basic attack damage and has a 40% chance to inflict Burn for 3 seconds.",
    "icon": "/images/skills/diamond/Fiery-Detonation.png",
    "effects": {
      "burn": true,
      "directdamage": true
    }
  },
  {
    "id": 7,
    "name": "Ice Shard",
    "type": "Active",
    "probability": 100,
    "description": "Launches an ice shard at the target, dealing damage equal to 180% of basic attack damage and has a 35% chance to inflict Slow for 2 seconds.",
    "icon": "/images/skills/diamond/Bloodstained-Icefield.png",
    "effects": {
      "slow": true,
      "directdamage": true
    }
  },
  {
    "id": 8,
    "name": "Berserker Rage",
    "type": "Passive",
    "probability": 100,
    "description": "Increases Attack of up to 4 ally troops in a circular range by 35% for 10 seconds. Also increases Rage generation by 50%.",
    "icon": "/images/skills/diamond/Berserk-Killing-Machine.png",
    "effects": {
      "rage": true,
      "buff": true
    }
  },
  {
    "id": 9,
    "name": "Silence",
    "type": "Command",
    "probability": 100,
    "description": "Silences the target for 3 seconds, preventing them from using active skills.",
    "icon": "/images/skills/diamond/Silencer.png",
    "effects": {
      "silence": true,
      "debuff": true
    }
  },
  {
    "id": 10,
    "name": "Disarm",
    "type": "Command",
    "probability": 100,
    "description": "Disarms the target for 2 seconds, reducing their attack damage by 50%.",
    "icon": "/images/skills/diamond/Disarmament.png",
    "effects": {
      "disarm": true,
      "debuff": true
    }
  },
  {
    "id": 11,
    "name": "Evasion",
    "type": "Passive",
    "probability": 100,
    "description": "Increases Evasion of up to 4 ally troops in a circular range by 25% for 8 seconds.",
    "icon": "/images/skills/diamond/On-Alert.png",
    "effects": {
      "evasion": true,
      "buff": true
    }
  },
  {
    "id": 12,
    "name": "Dispel",
    "type": "Active",
    "probability": 100,
    "description": "Removes all buffs from up to 3 enemy troops in a circular range.",
    "icon": "/images/skills/diamond/Blessed-Negation.png",
    "effects": {
      "dispel": true,
      "debuff": true
    }
  },
  {
    "id": 13,
    "name": "Broken Blade",
    "type": "Command",
    "probability": 100,
    "description": "Reduces the target's attack damage by 40% for 4 seconds.",
    "icon": "/images/skills/diamond/Broken-Armor.png",
    "effects": {
      "brokenblade": true,
      "debuff": true
    }
  },
  {
    "id": 14,
    "name": "Immunity Control",
    "type": "Passive",
    "probability": 100,
    "description": "Provides immunity to control effects for up to 4 ally troops in a circular range for 6 seconds.",
    "icon": "/images/skills/diamond/Divine-Shield.png",
    "effects": {
      "immunitycontrol": true,
      "buff": true
    }
  },
  {
    "id": 15,
    "name": "Devastation",
    "type": "Active",
    "probability": 100,
    "description": "Deals massive damage equal to 300% of basic attack damage to the target.",
    "icon": "/images/skills/diamond/Blow-of-Chaos.png",
    "effects": {
      "devastation": true,
      "directdamage": true
    }
  },
  {
    "id": 16,
    "name": "Damage Reduction",
    "type": "Passive",
    "probability": 100,
    "description": "Reduces damage taken by up to 4 ally troops in a circular range by 25% for 8 seconds.",
    "icon": "/images/skills/diamond/Divine-Shield.png",
    "effects": {
      "damagereduction": true,
      "buff": true
    }
  },
  {
    "id": 17,
    "name": "Retribution",
    "type": "Counterattack",
    "probability": 100,
    "description": "When attacked, reflects 30% of the damage back to the attacker.",
    "icon": "/images/skills/diamond/Shield-Reflector.png",
    "effects": {
      "retribution": true,
      "counterattack": true
    }
  },
  {
    "id": 18,
    "name": "Lacerate",
    "type": "Command",
    "probability": 100,
    "description": "Inflicts a deep wound on the target, causing them to bleed for 5 seconds with increased damage.",
    "icon": "/images/skills/diamond/Blood-Eagle-Punishment.png",
    "effects": {
      "lacerate": true,
      "bleed": true,
      "debuff": true
    }
  },
  {
    "id": 19,
    "name": "First Strike",
    "type": "Active",
    "probability": 100,
    "description": "Deals damage equal to 200% of basic attack damage and has a 40% chance to inflict Silence for 2 seconds.",
    "icon": "/images/skills/diamond/First-strike.png",
    "effects": {
      "directdamage": true,
      "silence": true
    }
  },
  {
    "id": 20,
    "name": "Enrage",
    "type": "Passive",
    "probability": 100,
    "description": "Increases Attack of up to 4 ally troops in a circular range by 35% for 10 seconds. Also increases Rage generation by 50%.",
    "icon": "/images/skills/diamond/Enrage.png",
    "effects": {
      "rage": true,
      "buff": true
    }
  },
  {
    "id": 21,
    "name": "Divine Blessing",
    "type": "Active",
    "probability": 100,
    "description": "Restores Health of up to 4 ally troops in a circular range by 25% of max HP. Also removes all debuffs from affected troops.",
    "icon": "/images/skills/diamond/Divine-Blessing.png",
    "effects": {
      "heal": true,
      "purify": true
    }
  },
  {
    "id": 22,
    "name": "Odins Asylum",
    "type": "Passive",
    "probability": 100,
    "description": "Provides immunity to control effects for up to 4 ally troops in a circular range for 6 seconds.",
    "icon": "/images/skills/diamond/Odins-Asylum.png",
    "effects": {
      "immunitycontrol": true,
      "buff": true
    }
  },
  {
    "id": 23,
    "name": "Rage Leech",
    "type": "Command",
    "probability": 100,
    "description": "When deployed Troop performs a basic attack, there is a 20% chance to steal 50 Rage from the target.",
    "icon": "/images/skills/diamond/Rage-Leech.png",
    "effects": {
      "rage": true,
      "basicattack": true
    }
  },
  {
    "id": 24,
    "name": "Hymn of Life",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Hymn-of-Life.png",
    "effects": {
      "heal": true,
      "buff": true
    }
  },
  {
    "id": 25,
    "name": "Rest and Counterattack",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Rest-and-Counterattack.png",
    "effects": {
      "counterattack": true,
      "heal": true
    }
  },
  {
    "id": 26,
    "name": "Deadly Counterattack",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Deadly-Counterattack.png",
    "effects": {
      "counterattack": true,
      "directdamage": true
    }
  },
  {
    "id": 27,
    "name": "Retaliate",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Retaliate.png",
    "effects": {
      "counterattack": true
    }
  },
  {
    "id": 28,
    "name": "Siege",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Siege.png",
    "effects": {
      "directdamage": true
    }
  },
  {
    "id": 29,
    "name": "Silent Invasion",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Silent-Invasion.png",
    "effects": {
      "silence": true,
      "directdamage": true
    }
  },
  {
    "id": 30,
    "name": "Solitude",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Solitude.png",
    "effects": {
      "buff": true
    }
  },
  {
    "id": 31,
    "name": "Splinter",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Splinter.png",
    "effects": {
      "directdamage": true
    }
  },
  {
    "id": 32,
    "name": "Tenacity",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Tenacity.png",
    "effects": {
      "buff": true
    }
  },
  {
    "id": 33,
    "name": "This Too Shall Pass",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/This-Too-Shall-Pass.png",
    "effects": {
      "purify": true
    }
  },
  {
    "id": 34,
    "name": "Thors Determination",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Thors-Determination.png",
    "effects": {
      "buff": true
    }
  },
  {
    "id": 35,
    "name": "Tidal Attack",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Tidal-Attack.png",
    "effects": {
      "directdamage": true
    }
  },
  {
    "id": 36,
    "name": "Trap of Despair",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Trap-of-Despair.png",
    "effects": {
      "debuff": true
    }
  },
  {
    "id": 37,
    "name": "Valkyries Gaze",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Valkyries-Gaze.png",
    "effects": {
      "buff": true
    }
  },
  {
    "id": 38,
    "name": "Venom Aggregation",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Venom-Agrregation.png",
    "effects": {
      "poison": true
    }
  },
  {
    "id": 39,
    "name": "Wild Indulgence",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Wild-Indulgence.png",
    "effects": {
      "rage": true
    }
  },
  {
    "id": 40,
    "name": "Divine Shield",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Divine-Shield.png",
    "effects": {
      "shield": true,
      "buff": true
    }
  },
  {
    "id": 41,
    "name": "Blessed by Fate",
    "type": "N/A",
    "probability": 0,
    "description": "Skill details coming soon.",
    "icon": "/images/skills/diamond/Blessed-by-Fate.png",
    "effects": {
      "buff": true
    }
  }
];
